<?php
/**
 * UI Import runs in bulk-save mode, which suppresses the mirror guard's save events.
 * Vtiger's loader prefers modules/<Module>/views/Import.php (<Module>_Import_View) over
 * Vtiger_Import_View, as core Calendar and Users do; these overrides deny every mode
 * for every user. isPermitted() answers yes for administrators, so profiles cannot.
 */
trait VemsImportDenied {
    public function checkPermission(Vtiger_Request $request) {
        throw new AppException(vtranslate('LBL_PERMISSION_DENIED'));
    }

    public function process(Vtiger_Request $request) {
        throw new AppException(vtranslate('LBL_PERMISSION_DENIED'));
    }
}

const VEMS_IMPORT_GUARD_MARKER = 'V-EMS import guard';

function vemsImportViewSource(string $module): string {
    if (!preg_match('/^[A-Za-z][A-Za-z0-9]*$/', $module)) throw new RuntimeException('Invalid module name for import guard');
    return "<?php\n// " . VEMS_IMPORT_GUARD_MARKER . ": generated by install-mirror-guard.php\n"
        . "require_once '/opt/vems/ImportGuard.php';\n"
        . "class {$module}_Import_View extends Vtiger_Import_View { use VemsImportDenied; }\n";
}
