export const RBAC_POLICIES = [
  { pattern: /^\/api\/patient-cases\/PCR-[0-9]{6,}\/(demographics|assessments|observations|medications|procedures|disposition|timeline)$/, method: 'GET', roles: ['field_crew','field_crew_lead','clinical_reviewer','supervisor','sys_admin'] },
  { pattern: /^\/api\/patient-cases\/PCR-[0-9]{6,}\/demographics$/, method: 'PUT', roles: ['field_crew','field_crew_lead','supervisor','sys_admin'] },
  { pattern: /^\/api\/patient-cases\/PCR-[0-9]{6,}\/(assessments|observations|medications|procedures|disposition)$/, method: 'POST', roles: ['field_crew','field_crew_lead','supervisor','sys_admin'] },
  { pattern: /^\/api\/incidents\/INC-[0-9]{6}\/patient-cases$/, method: 'GET', roles: ['dispatcher','field_crew','field_crew_lead','clinical_reviewer','supervisor','sys_admin'] },
  { pattern: /^\/api\/incidents\/INC-[0-9]{6}\/patient-cases$/, method: 'POST', roles: ['dispatcher','field_crew','field_crew_lead','supervisor','sys_admin'] },
  { pattern: /^\/api\/patient-cases\/PCR-[0-9]{6,}(?:\/(patient-link|encounter))?$/, method: 'GET', roles: ['dispatcher','field_crew','field_crew_lead','clinical_reviewer','supervisor','sys_admin'] },
  { pattern: /^\/api\/patient-cases\/PCR-[0-9]{6,}\/(patient-link|encounters|provisional-patient)$/, method: 'POST', roles: ['field_crew','field_crew_lead','supervisor','sys_admin'] },
  { pattern: /^\/api\/patient-cases\/PCR-[0-9]{6,}\/identity-reconciliation$/, method: 'POST', roles: ['supervisor','sys_admin'] },
  { pattern: /^\/api\/patient-cases\/PCR-[0-9]{6,}\/(assignment|status)$/, method: 'PATCH', roles: ['field_crew_lead','supervisor','sys_admin'] },

  { pattern: /^\/api\/support\/diagnostics$/, method: "GET", roles: ["supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/support\/sync-intents\/([0-9]+)\/replay$/, method: "POST", roles: ["operations_manager", "sys_admin"] },
  { pattern: /^\/api\/incidents$/, method: "GET", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/incidents$/, method: "POST", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/incidents\/(INC-[0-9]{6})$/, method: "GET", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/incidents\/(INC-[0-9]{6})$/, method: "PATCH", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/incidents\/(INC-[0-9]{6})\/assignments$/, method: "POST", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/incidents\/(INC-[0-9]{6})\/patient-link$/, method: "GET", roles: ["field_crew", "field_crew_lead", "clinical_reviewer", "supervisor", "sys_admin"] },
  { pattern: /^\/api\/incidents\/(INC-[0-9]{6})\/encounters$/, method: "GET", roles: ["field_crew", "field_crew_lead", "clinical_reviewer", "supervisor", "sys_admin"] },
  { pattern: /^\/api\/encounters\/([^/]+)\/interventions$/, method: "GET", roles: ["field_crew", "field_crew_lead", "clinical_reviewer", "supervisor", "sys_admin"] },
  { pattern: /^\/api\/encounters\/([^/]+)\/handover$/, method: "GET", roles: ["field_crew", "field_crew_lead", "clinical_reviewer", "supervisor", "sys_admin"] },
  { pattern: /^\/api\/assignments\/(ASN-[0-9]{6})$/, method: "PATCH", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/patients\/search$/, method: "POST", roles: ["dispatcher", "field_crew", "field_crew_lead", "supervisor", "clinical_reviewer", "sys_admin"] },
  { pattern: /^\/api\/patients$/, method: "POST", roles: ["field_crew", "field_crew_lead", "clinical_reviewer", "supervisor", "sys_admin"] },
  { pattern: /^\/api\/vehicles$/, method: "GET", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/vehicles$/, method: "POST", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/vehicles\/AMB-[0-9]{3,}$/, method: "GET", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/vehicles\/AMB-[0-9]{3,}$/, method: "PATCH", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/personnel$/, method: "GET", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/personnel$/, method: "POST", roles: ["supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/personnel\/STAFF-[0-9]{3,}$/, method: "GET", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/personnel\/STAFF-[0-9]{3,}$/, method: "PATCH", roles: ["supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/stock-items$/, method: "GET", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/stock-items$/, method: "POST", roles: ["supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/stock-items\/ITEM-[0-9]{3,}$/, method: "GET", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/stock-items\/ITEM-[0-9]{3,}$/, method: "PATCH", roles: ["supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/vehicles\/AMB-[0-9]{3,}\/stock$/, method: "GET", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/vehicles\/AMB-[0-9]{3,}\/stock\/ITEM-[0-9]{3,}\/adjustments$/, method: "POST", roles: ["dispatcher", "supervisor", "operations_manager", "sys_admin"] },
  { pattern: /^\/api\/incidents\/(INC-[0-9]{6})\/patient-link$/, method: "POST", roles: ["dispatcher", "field_crew", "field_crew_lead", "clinical_reviewer", "supervisor", "sys_admin"] },
  { pattern: /^\/api\/incidents\/(INC-[0-9]{6})\/encounters$/, method: "POST", roles: ["field_crew", "field_crew_lead", "clinical_reviewer", "supervisor", "sys_admin"] },
  { pattern: /^\/api\/encounters\/([^/]+)\/observations$/, method: "POST", roles: ["field_crew", "field_crew_lead", "clinical_reviewer", "supervisor", "sys_admin"] },
  { pattern: /^\/api\/encounters\/([^/]+)\/interventions$/, method: "POST", roles: ["field_crew", "field_crew_lead", "clinical_reviewer", "supervisor", "sys_admin"] },
  { pattern: /^\/api\/encounters\/([^/]+)\/handover$/, method: "POST", roles: ["field_crew", "field_crew_lead", "clinical_reviewer", "supervisor", "sys_admin"] }
];
